apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-{{ .Values.application.name }}"
  namespace: "{{ .Release.Namespace}}"
spec:
  ports:
    - port: 8080
      protocol: "TCP"
      targetPort: 8080
  selector:
    app: "{{ .Release.Name }}-{{ .Values.application.name }}"
  sessionAffinity: "None"

  